Repository Azure/karpenter-provider-azure, pull requests merged in 2024-03, with the labels that each got.

#173 fix: add topology.disk.csi.azure.com/zone to normalized labels
  pkg/apis/v1alpha2/labels.go
  pkg/operator/operator.go
  pkg/providers/instancetype/instancetype.go
  pkg/providers/instancetype/suite_test.go
  pkg/test/environment.go
Labels: kind/bug, area/storage

#204 chore: remove unused SKU selection labels
  pkg/apis/v1alpha2/labels.go
  pkg/providers/instancetype/suite_test.go
Labels: kind/cleanup, area/api

#214 chore(release): onboard to 1ES
  .github/workflows/build-publish-mcr.yml
Labels: area/security, area/artifacts, area/ci, area/release

#220 fix: managed identity not being enabled for nodes
  pkg/providers/imagefamily/bootstrap/aksbootstrap.go
Labels: kind/bug, area/nap, area/security

#230 perf: instance types cache
  pkg/cache/cache.go
  pkg/cache/unavailableofferings.go
  pkg/providers/instancetype/instancetypes.go
Labels: area/instance-types, area/performance, area/unavailable-offerings
