Repository Azure/karpenter-provider-azure, pull requests merged in 2024-12, with the labels that each got.

#587 fix: GPU bootstrap, refresh driver versions and list of supported GPU VM SKUs
  .pre-commit-config.yaml
  go.mod
  pkg/controllers/nodeclass/hash/controller.go
  pkg/providers/imagefamily/azlinux.go
  pkg/providers/imagefamily/bootstrap/aksbootstrap.go
  pkg/providers/imagefamily/bootstrap/bootstrap.go
  pkg/providers/imagefamily/bootstrap/cse_cmd.sh.gtpl
  pkg/providers/imagefamily/ubuntu_2204.go
  pkg/providers/instancetype/suite_test.go
  pkg/providers/launchtemplate/launchtemplate.go
  pkg/providers/launchtemplate/parameters/types.go
  pkg/utils/gpu.go
  pkg/utils/gpu_test.go
  pkg/utils/supported-gpus.yaml
  typos.toml
Labels: area/gpu, area/bootstrap

#589 chore: bump tool versions
  hack/toolchain.sh
Labels: area/devtools, area/dependency

#591 chore: bump devcontainer go version
  .devcontainer/Dockerfile
Labels: area/devtools, area/dependency

#586 deps: bump sigs.k8s.io/karpenter to v1.0.5
  charts/karpenter-crd/templates/karpenter.sh_nodeclaims.yaml
  charts/karpenter-crd/templates/karpenter.sh_nodepools.yaml
  go.mod
  go.sum
  hack/mutation/conversion_webhooks_injection.sh
  pkg/apis/crds/karpenter.sh_nodeclaims.yaml
  pkg/apis/crds/karpenter.sh_nodepools.yaml
  pkg/cloudprovider/suite_test.go
  pkg/controllers/nodeclaim/garbagecollection/suite_test.go
  pkg/providers/instance/suite_test.go
  pkg/providers/instancetype/suite_test.go
Labels: area/dependency

#590 chore: add aks-node-viewer
  Makefile-az.mk
  hack/toolchain.sh
Labels: area/devtools

#595 fix: E2E node expiration test
  test/suites/integration/expiration_test.go
Labels: area/e2e-testing

#599 chore: refresh monitoring deployment
  hack/monitoring/grafana-values.yaml
  hack/monitoring/karpenter-performance-dashboard.json
  hack/monitoring/prometheus-values.yaml
Labels: area/metrics, area/devtools, area/performance

#602 chore: fix install-deps action and dependabot config
  .github/actions/install-deps/action.yaml
  .github/dependabot.yaml
Labels: area/ci

#596 chore: refresh E2E test expectation helpers
  test/pkg/environment/common/expectations.go
Labels: area/e2e-test-framework

#606 chore: update Makefile test targets
  Makefile
Labels: area/testing, area/ci

#617 fix: temp exclude SKUs without compatible VM image
  hack/codegen.sh
  pkg/fake/zz_generated.sku.eastus.go
  pkg/fake/zz_generated.sku.westcentralus.go
  pkg/providers/instancetype/instancetypes.go
  pkg/providers/instancetype/suite_test.go
Labels: area/vm-images, area/provisioning

#618 chore: update static pricing
  pkg/providers/pricing/zz_generated.pricing.go
Labels: area/pricing

#628 [release-0.5.x] fix: exclude SKUs without compatible VM image and fix GPU bootstrap
  .github/workflows/ci-test.yml
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  go.mod
  hack/codegen.sh
  hack/toolchain.sh
  pkg/fake/zz_generated.sku.eastus.go
  pkg/fake/zz_generated.sku.westcentralus.go
  pkg/providers/imagefamily/azlinux.go
  pkg/providers/imagefamily/bootstrap/aksbootstrap.go
  pkg/providers/imagefamily/bootstrap/bootstrap.go
  pkg/providers/imagefamily/bootstrap/cse_cmd.sh.gtpl
  pkg/providers/imagefamily/ubuntu_2204.go
  pkg/providers/instancetype/instancetypes.go
  pkg/providers/instancetype/suite_test.go
  pkg/providers/launchtemplate/launchtemplate.go
  pkg/providers/launchtemplate/parameters/types.go
  pkg/test/expectations/expectations.go
  pkg/utils/gpu.go
  pkg/utils/gpu_test.go
  pkg/utils/supported-gpus.yaml
  typos.toml
Labels: area/vm-images, area/provisioning

#526 feat: ListNodeImageVersions + shared image gallery support
  Makefile-az.mk
  karpenter-values-template.yaml
  pkg/cloudprovider/drift.go
  pkg/cloudprovider/suite_test.go
  pkg/fake/nodeimageversionsapi.go
  pkg/fake/nodeimageversionsapi_test.go
  pkg/operator/operator.go
  pkg/operator/options/options.go
  pkg/providers/imagefamily/azlinux.go
  pkg/providers/imagefamily/image.go
  pkg/providers/imagefamily/image_test.go
  pkg/providers/imagefamily/nodeimageversionsclient.go
  pkg/providers/imagefamily/nodeimageversionsclient_test.go
  pkg/providers/imagefamily/types.go
  pkg/providers/imagefamily/ubuntu_2204.go
  pkg/providers/instance/azure_client.go
  pkg/providers/instance/instance.go
  pkg/providers/instancetype/instancetypes.go
  pkg/providers/instancetype/suite_test.go
  pkg/test/environment.go
  pkg/test/options.go
Labels: area/nap, area/vm-images
