Repository Azure/karpenter-provider-azure, pull requests merged in 2024-04, with the labels that each got.

#255 chore: bumping go to 1.22
  .devcontainer/devcontainer.json
  go.mod
  go.sum
Labels: area/networking, area/security, area/devtools, area/dependency, area/ci

#238 feat: support custom subnet ID (`--vnet-subnet-id`)
  .github/actions/e2e/install-karpenter/action.yaml
  Makefile-az.mk
  pkg/auth/config.go
  pkg/auth/config_test.go
  pkg/operator/operator.go
  pkg/operator/options/options.go
  pkg/operator/options/options_validation.go
  pkg/operator/options/suite_test.go
  pkg/providers/imagefamily/azlinux.go
  pkg/providers/imagefamily/bootstrap/aksbootstrap.go
  pkg/providers/imagefamily/bootstrap/bootstrap.go
  pkg/providers/imagefamily/resolver.go
  pkg/providers/imagefamily/ubuntu_2204.go
  pkg/providers/instance/azure_client.go
  pkg/providers/instancetype/suite_test.go
  pkg/providers/launchtemplate/launchtemplate.go
  pkg/providers/launchtemplate/parameters/types.go
  pkg/test/environment.go
  pkg/test/options.go
  pkg/utils/subnet_parser.go
  pkg/utils/subnet_parser_test.go
  skaffold.yaml
Labels: kind/feature, area/networking

#147 feat: add release scripts
  .ko.yaml
  .shellcheckrc
  Makefile
  Makefile-az.mk
  charts/karpenter/values.yaml
  hack/infra/ksnap-acr.bicep
  hack/release/common.sh
  hack/release/release.sh
  hack/release/snapshot.sh
  hack/toolchain.sh
Labels: area/artifacts, size/L, area/release

#260 chore: update to sig.k8s.io/karpenter v0.36.0
  go.mod
  go.sum
  pkg/apis/crds/karpenter.sh_nodeclaims.yaml
  pkg/apis/crds/karpenter.sh_nodepools.yaml
  pkg/apis/v1alpha2/nodepool_validation_cel_test.go
  pkg/cloudprovider/cloudprovider.go
  pkg/cloudprovider/suite_test.go
  pkg/providers/imagefamily/bootstrap/aksbootstrap.go
  pkg/providers/imagefamily/resolver.go
  pkg/providers/instance/instance.go
  pkg/providers/instancetype/instancetypes.go
  pkg/providers/instancetype/suite_test.go
  test/pkg/environment/azure/environment.go
  test/suites/chaos/suite_test.go
  test/suites/drift/suite_test.go
  test/suites/gpu/suite_test.go
  test/suites/nodeclaim/nodeclaim_test.go
  test/suites/utilization/suite_test.go
Labels: size/L, area/dependency

#261 chore: update dev tools
  .devcontainer/Dockerfile
  .golangci.yaml
  Makefile
  hack/toolchain.sh
Labels: size/S, area/devtools

#148 feat: add Helm-based install process
  .github/actions/e2e/install-karpenter/action.yaml
  .gitignore
  Makefile-az.mk
  README.md
  hack/deploy/configure-values.sh
  hack/deploy/create-cluster.sh
  karpenter-values-template.yaml
  skaffold.yaml
Labels: area/artifacts, size/L, area/documentation, area/release

#279 chore(release): add execute perms to release.sh
  hack/release/release.sh
Labels: size/XS, area/release

#290 chore(make): fix create-cluster.sh deployment script to work with correct namespace
  Makefile
  Makefile-az.mk
  README.md
  hack/deploy/create-cluster.sh
Labels: area/devtools, area/documentation

#274 feat: CEL validation for provider-specific labels/requirements
  Makefile
  Makefile-az.mk
  hack/validation/common.sh
  hack/validation/labels.sh
  hack/validation/requirements.sh
  pkg/apis/crds/karpenter.sh_nodeclaims.yaml
  pkg/apis/crds/karpenter.sh_nodepools.yaml
Labels: area/api-validation, size/M

#246 fix: Apply Tags consistently across NIC, VM and Disks
  pkg/operator/options/suite_test.go
  pkg/providers/instance/instance.go
  pkg/providers/instance/suite_test.go
Labels: area/networking

#304 deps: bump upstream Karpenter to v0.36.1
  go.mod
  go.sum
Labels: size/XS, area/dependency

#301 fix: propagate kubelet identity into node identities
  hack/deploy/configure-values.sh
  karpenter-values-template.yaml
Labels: area/security, size/XS, area/artifacts
