Repository Azure/karpenter-provider-azure, pull requests merged in 2024-10, with the labels that each got.

#467 fix: disable IP forwarding
  pkg/providers/instance/instance.go
Labels: kind/bug, area/networking

#508 test(Cilium): add CiliumAgentNotReadyTaint to prevent overprovisioning
  examples/v1beta1/general-purpose.yaml
  examples/v1beta1/multi-arch.yaml
  examples/v1beta1/system-surge.yaml
  test/pkg/environment/azure/environment.go
Labels: area/nap, area/networking

#516 fix(provisioning): add cilium taint and label
  examples/v1beta1/general-purpose.yaml
  examples/v1beta1/multi-arch.yaml
  examples/v1beta1/system-surge.yaml
  test/pkg/environment/azure/environment.go
Labels: area/networking, area/e2e-test-framework, area/provisioning

#486 feat: BYO Subnet Per AKSNodeClass + Subnet Drift
  pkg/apis/crds/karpenter.azure.com_aksnodeclasses.yaml
  pkg/apis/v1alpha2/aksnodeclass.go
  pkg/apis/v1alpha2/crd_validation_cel_test.go
  pkg/cloudprovider/cloudprovider.go
  pkg/cloudprovider/drift.go
  pkg/cloudprovider/suite_test.go
  pkg/operator/operator.go
  pkg/operator/options/options.go
  pkg/providers/instance/armutils.go
  pkg/providers/instance/azure_client.go
  pkg/providers/instance/instance.go
  pkg/providers/instance/instance_test.go
  pkg/providers/instancetype/suite_test.go
  pkg/providers/launchtemplate/launchtemplate.go
  pkg/test/environment.go
  pkg/test/options.go
  test/pkg/environment/common/expectations.go
  test/suites/drift/suite_test.go
Labels: area/networking

#533 ci: add dl.k8s.io to egress policy allowlist for toolchain
  .github/workflows/ci-test.yml
  .github/workflows/ci.yml
  hack/toolchain.sh
Labels: area/security, area/ci

#529 docs: Updates README.md instructions to remove inconsistency between versions
  README.md
Labels: size/XS, area/documentation

#537 Make webhooks work in AKS CCP context
  .golangci.yaml
  cmd/controller/main_ccp.go
  go.mod
  pkg/alt/karpenter-core/pkg/operator/operator.go
  pkg/alt/karpenter-core/pkg/webhooks/README.md
  pkg/alt/karpenter-core/pkg/webhooks/webhooks.go
  pkg/alt/knative/pkg/webhook/resourcesemantics/conversion/README.md
  pkg/alt/knative/pkg/webhook/resourcesemantics/conversion/controller.go
  pkg/alt/knative/pkg/webhook/resourcesemantics/conversion/conversion.go
  pkg/alt/knative/pkg/webhook/resourcesemantics/conversion/conversion_test.go
  pkg/alt/knative/pkg/webhook/resourcesemantics/conversion/internal/types.go
  pkg/alt/knative/pkg/webhook/resourcesemantics/conversion/internal/zz_generated.deepcopy.go
  pkg/alt/knative/pkg/webhook/resourcesemantics/conversion/options.go
  pkg/alt/knative/pkg/webhook/resourcesemantics/conversion/options_test.go
  pkg/alt/knative/pkg/webhook/resourcesemantics/conversion/reconciler.go
  pkg/alt/knative/pkg/webhook/resourcesemantics/conversion/table_test.go
  pkg/operator/operator.go
Labels: area/nap, area/api

#530 Replace VNET_SUBNET_ID source in configure-values.sh.
  hack/deploy/configure-values.sh
Labels: area/networking, area/devtools
