Repository Azure/karpenter-provider-azure, pull requests merged in 2024-02, with the labels that each got.

#131 chore: create resource group before creating workload identity for local dev
  Makefile-az.mk
Labels: area/devtools

#87 docs: Update CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: kind/documentation, area/developer-guide

#143 chore: remove custom kubebuilder assets location
  .devcontainer/devcontainer.json
Labels: area/testing, area/devtools

#139 chore(karpenter-core): go get github.com/aws/karpenter-core@v0.32.2-0.20231122223643-d0156e68fd30 (1/6)
  go.mod
  go.sum
  pkg/apis/crds/karpenter.sh_nodepools.yaml
  pkg/cloudprovider/cloudprovider.go
  pkg/cloudprovider/suite_test.go
  test/pkg/environment/common/expectations.go
Labels: area/dependency

#151 chore(karpenter-core): go get sigs.k8s.io/karpenter@v0.33.0 (6/6)
  go.mod
  go.sum
Labels: area/dependency

#149 chore(karpenter-core): go get sigs.k8s.io/karpenter@v0.32.2-0.20231205044115-1cf3df4ba3cc (5/6)
  charts/karpenter-crd/templates/karpenter.sh_machines.yaml
  charts/karpenter-crd/templates/karpenter.sh_provisioners.yaml
  charts/karpenter/templates/webhooks-core.yaml
  designs/gpu-selection-and-bootstrap.md
  go.mod
  go.sum
  pkg/alt/karpenter-core/pkg/operator/operator.go
  pkg/apis/crds/karpenter.sh_machines.yaml
  pkg/apis/crds/karpenter.sh_provisioners.yaml
  pkg/apis/v1alpha2/labels.go
  pkg/providers/instance/instance.go
  pkg/providers/instance/suite_test.go
  pkg/providers/instancetype/suite_test.go
  pkg/webhooks/webhooks.go
  test/pkg/debug/node.go
  test/pkg/environment/common/expectations.go
  test/pkg/environment/common/monitor.go
  test/pkg/environment/common/setup.go
Labels: area/dependency

#142 chore(karpenter-core): go get sigs.k8s.io/karpenter@v0.32.2-0.20231129204947-79dc3457680f (4/6)
  Makefile-az.mk
  charts/karpenter-crd/templates/karpenter.sh_machines.yaml
  charts/karpenter-crd/templates/karpenter.sh_provisioners.yaml
  charts/karpenter/templates/deployment.yaml
  charts/karpenter/templates/webhooks-core.yaml
  charts/karpenter/values.yaml
  designs/gpu-selection-and-bootstrap.md
  go.mod
  go.sum
  pkg/alt/karpenter-core/pkg/operator/operator.go
  pkg/apis/apis.go
  pkg/apis/crds/karpenter.sh_machines.yaml
  pkg/apis/crds/karpenter.sh_provisioners.yaml
  pkg/apis/settings/settings.go
  pkg/apis/settings/suite_test.go
  pkg/apis/settings/zz_generated.deepcopy.go
  pkg/apis/v1alpha2/labels.go
  pkg/cloudprovider/cloudprovider.go
  pkg/operator/operator.go
  pkg/operator/options/options.go
  pkg/operator/options/options_validation.go
  pkg/operator/options/suite_test.go
  pkg/providers/instance/instance.go
  pkg/providers/instance/suite_test.go
  pkg/providers/instancetype/suite_test.go
  pkg/test/environment.go
  pkg/test/settings.go
  pkg/webhooks/webhooks.go
  skaffold.yaml
  test/pkg/debug/node.go
  test/pkg/environment/common/environment.go
  test/pkg/environment/common/expectations.go
  test/pkg/environment/common/monitor.go
  test/pkg/environment/common/setup.go
Labels: area/dependency

#161 Update build-publish-mcr.yml to reference correct repo
  .github/workflows/build-publish-mcr.yml
Labels: area/artifacts, area/release
