Repository Azure/karpenter-provider-azure, pull requests merged in 2024-07, with the labels that each got.

#433 chore(release): configure semantic-release automation
  .github/workflows/release-trigger.yaml
  .releaserc.json
  .releaserc.yaml
Labels: area/artifacts, area/ci, area/release

#440 test(e2e): switch to westus3 for e2e
  .github/workflows/e2e-matrix-trigger.yaml
Labels: area/ci

#441 fix: update skaffold version (E2E and devcontainer)
  .devcontainer/Dockerfile
  .github/workflows/e2e.yaml
Labels: area/devtools, area/dependency, area/ci

#429 fix(bootstrap): OOT credential provider support in 1.30+
  pkg/providers/imagefamily/bootstrap/aksbootstrap.go
  pkg/providers/imagefamily/bootstrap/aksbootstrap_test.go
  pkg/providers/instance/instance.go
  pkg/providers/instancetype/suite_test.go
  pkg/utils/utils.go
Labels: kind/bug, area/bootstrap

#442 docs(readme): update version to 0.5.1
  README.md
Labels: size/XS, area/documentation, area/release
