Repository Azure/karpenter-provider-azure, pull requests merged in 2024-06, with the labels that each got.

#381 chore: bumping the grid driver affecting linux kernels 5.15.1063+ versions
  pkg/utils/gpu.go
  pkg/utils/gpu_test.go
Labels: area/gpu

#414 fix: specify location when creating ACR
  .github/workflows/e2e-matrix-trigger.yaml
  .github/workflows/e2e.yaml
  Makefile-az.mk
Labels: area/ci

#391 fix: long running setup for expired auth token track 2 bug
  pkg/auth/cred.go
  pkg/providers/instance/azure_client.go
Labels: kind/bug
