Repository Azure/karpenter-provider-azure, pull requests merged in 2024-11, with the labels that each got.

#564 docs(self-hosted): Update Readme
  README.md
Labels: kind/documentation, area/devtools, area/documentation

#541 chore: add v1 NodePool examples
  examples/v1/general-purpose.yaml
  examples/v1/system-surge.yaml
Labels: size/S, area/documentation, area/api

#567 docs(workshop): KubeCon Azure workshop docs
  docs/workshops/10_multi_node_consolidation.md
  docs/workshops/1_install_karpenter.md
  docs/workshops/2_basic_nodepool.md
  docs/workshops/6_drift.md
  docs/workshops/9_single_node_consolidation.md
  docs/workshops/kubecon_azure_track.md
  docs/workshops/reestablish_env.md
Labels: area/documentation
