Repository Azure/karpenter-provider-azure, pull requests merged in 2025-04, with the labels that each got.

#641 test(e2e): update termination suite
  test/suites/integration/emptiness_test.go
  test/suites/integration/termination_grace_period_test.go
  test/suites/integration/termination_test.go
Labels: area/e2e-testing

#766 test(integration): mark "drain pods in order" as pending
  .pre-commit-config.yaml
  charts/karpenter-crd/templates/karpenter.azure.com_aksnodeclasses.yaml
  pkg/apis/crds/karpenter.azure.com_aksnodeclasses.yaml
  test/suites/integration/termination_test.go
Labels: area/e2e-testing

#768 chore: bump versions of pre-commit hooks
  .pre-commit-config.yaml
Labels: area/devtools

#773 fix(bootstrapping): Refactor bootstrapping to encapsulate between provisioning
  pkg/providers/imagefamily/bootstrap/aksbootstrap.go
  pkg/providers/imagefamily/bootstrap/staticvalues.go
Labels: area/bootstrap

#650 test(e2e): update drift suite
  pkg/apis/v1alpha2/aksnodeclass.go
  pkg/apis/v1alpha2/aksnodeclass_hash_test.go
  pkg/controllers/nodeclass/hash/controller.go
  pkg/controllers/nodeclass/hash/suite_test.go
  pkg/test/nodeclass.go
  test/pkg/environment/azure/environment.go
  test/pkg/environment/common/environment.go
  test/pkg/environment/common/expectations.go
  test/pkg/environment/common/setup.go
  test/suites/chaos/suite_test.go
  test/suites/drift/suite_test.go
  test/suites/gpu/suite_test.go
  test/suites/utilization/suite_test.go
Labels: area/e2e-test-framework, area/aksnodeclass, area/e2e-testing, area/drift

#765 test(upgrade): add Kubernetes Upgrade E2E test suite
  .github/workflows/e2e-matrix.yaml
  go.mod
  test/pkg/environment/azure/environment.go
  test/pkg/environment/azure/expectations.go
  test/pkg/environment/common/expectations.go
  test/suites/kubernetesupgrade/suite_test.go
Labels: area/e2e-testing, area/upgrade, area/drift

#803 chore: bump Go mod version
  go.mod
Labels: dependencies, area/security, area/devtools

#754 chore(upstream): bump upstream core version to v1.0.6
  charts/karpenter-crd/templates/karpenter.sh_nodeclaims.yaml
  charts/karpenter-crd/templates/karpenter.sh_nodepools.yaml
  go.mod
  go.sum
  pkg/apis/crds/karpenter.sh_nodeclaims.yaml
  pkg/apis/crds/karpenter.sh_nodepools.yaml
Labels: area/dependency

#729 feat(upgrade): adding new NodeClass status controller logic for upgrades of k8s, and node image versions
  charts/karpenter-crd/templates/karpenter.azure.com_aksnodeclasses.yaml
  cmd/controller/main.go
  cmd/controller/main_ccp.go
  pkg/apis/crds/karpenter.azure.com_aksnodeclasses.yaml
  pkg/apis/v1alpha2/aksnodeclass_status.go
  pkg/apis/v1alpha2/zz_generated.deepcopy.go
  pkg/controllers/controllers.go
  pkg/controllers/nodeclaim/inplaceupdate/controller.go
  pkg/controllers/nodeclass/hash/controller.go
  pkg/controllers/nodeclass/status/controller.go
  pkg/controllers/nodeclass/status/images.go
  pkg/controllers/nodeclass/status/images_test.go
  pkg/controllers/nodeclass/status/kubernetesversion.go
  pkg/controllers/nodeclass/status/kubernetesversion_test.go
  pkg/controllers/nodeclass/status/suite_test.go
  pkg/controllers/nodeclass/termination/controller.go
  pkg/controllers/nodeclass/termination/suite_test.go
  pkg/fake/communityimageversionsapi.go
  pkg/fake/nodeimageversionsapi.go
  pkg/providers/imagefamily/image.go
  pkg/providers/imagefamily/kubernetesversion.go
  pkg/providers/imagefamily/nodeimage.go
  pkg/providers/imagefamily/nodeimage_test.go
  pkg/providers/imagefamily/resolver.go
  pkg/providers/imagefamily/suite_test.go
  pkg/test/environment.go
Labels: area/vm-images, area/upgrade, api-review

#807 chore: bump tooling versions
  hack/toolchain.sh
Labels: area/devtools

#601 chore: update sigs.k8s.io/karpenter to v1.4.0
  charts/karpenter-crd/templates/karpenter.sh_nodeclaims.yaml
  charts/karpenter-crd/templates/karpenter.sh_nodepools.yaml
  charts/karpenter/templates/deployment.yaml
  charts/karpenter/values.yaml
  cmd/controller/main.go
  cmd/controller/main_ccp.go
  go.mod
  go.sum
  hack/validation/labels.sh
  hack/validation/requirements.sh
  pkg/alt/karpenter-core/pkg/operator/logger.go
  pkg/alt/karpenter-core/pkg/operator/operator.go
  pkg/alt/karpenter-core/pkg/webhooks/README.md
  pkg/alt/karpenter-core/pkg/webhooks/webhooks.go
  pkg/alt/knative/pkg/webhook/resourcesemantics/conversion/README.md
  pkg/alt/knative/pkg/webhook/resourcesemantics/conversion/controller.go
  pkg/alt/knative/pkg/webhook/resourcesemantics/conversion/conversion.go
  pkg/alt/knative/pkg/webhook/resourcesemantics/conversion/conversion_test.go
  pkg/alt/knative/pkg/webhook/resourcesemantics/conversion/internal/types.go
  pkg/alt/knative/pkg/webhook/resourcesemantics/conversion/internal/zz_generated.deepcopy.go
  pkg/alt/knative/pkg/webhook/resourcesemantics/conversion/options.go
  pkg/alt/knative/pkg/webhook/resourcesemantics/conversion/options_test.go
  pkg/alt/knative/pkg/webhook/resourcesemantics/conversion/reconciler.go
  pkg/alt/knative/pkg/webhook/resourcesemantics/conversion/table_test.go
  pkg/apis/crds/karpenter.sh_nodeclaims.yaml
  pkg/apis/crds/karpenter.sh_nodepools.yaml
  pkg/cloudprovider/cloudprovider.go
  pkg/cloudprovider/suite_test.go
  pkg/controllers/nodeclaim/garbagecollection/suite_test.go
  pkg/operator/operator.go
  pkg/providers/instance/instance.go
  pkg/providers/instance/instance_test.go
  pkg/providers/instance/suite_test.go
  pkg/providers/instancetype/instancetype.go
  pkg/providers/instancetype/instancetypes.go
  pkg/providers/instancetype/suite_test.go
  pkg/test/environment.go
  test/pkg/debug/node.go
  test/pkg/debug/nodeclaim.go
  test/pkg/debug/pod.go
  test/pkg/environment/common/expectations.go
  test/suites/chaos/suite_test.go
  test/suites/integration/repair_policy_test.go
  test/suites/integration/termination_test.go
  test/suites/nodeclaim/nodeclaim_test.go
Labels: area/dependency

#813 fix: pin skaffold version (and have e2e match dev)
  .devcontainer/devcontainer.json
  .github/workflows/e2e.yaml
Labels: area/e2e-test-framework, area/devtools, area/ci

#814 fix(ci): remove `--until-it-fails` from `make deflake`
  Makefile
Labels: area/testing, area/ci

#811 chore: update versions of credential provider (and add 1.32)
  pkg/providers/imagefamily/bootstrap/aksbootstrap.go
  pkg/providers/imagefamily/bootstrap/aksbootstrap_test.go
Labels: area/provisioning, area/dependency

#810 chore: update CodeQL config
  .github/workflows/codeql-analysis.yml
  Makefile-az.mk
Labels: area/security, area/devtools, area/ci

#825 chore: update static list of zonal regions
  pkg/providers/instancetype/instancetypes.go
Labels: area/availability-zones

#841 feat: improve kubectl get UX
  Makefile
  charts/karpenter-crd/templates/karpenter.azure.com_aksnodeclasses.yaml
  charts/karpenter-crd/templates/karpenter.sh_nodeclaims.yaml
  charts/karpenter-crd/templates/karpenter.sh_nodepools.yaml
  hack/mutation/kubectl_get_ux.sh
  pkg/apis/crds/karpenter.azure.com_aksnodeclasses.yaml
  pkg/apis/crds/karpenter.sh_nodeclaims.yaml
  pkg/apis/crds/karpenter.sh_nodepools.yaml
  pkg/apis/v1alpha2/aksnodeclass.go
Labels: area/api

#847 fix: take test options from context
  pkg/apis/v1alpha2/suite_test.go
  pkg/controllers/nodeclaim/inplaceupdate/suite_test.go
  pkg/test/environment.go
Labels: area/testing
