Repository Azure/karpenter-provider-azure, pull requests merged in 2025-02, with the labels that each got.

#678 chore: bump go minor version to 1.23.6
  go.mod
Labels: area/security, area/devtools

#677 fix(API): add missing validation rules for v1beta1
  charts/karpenter-crd/templates/karpenter.sh_nodeclaims.yaml
  charts/karpenter-crd/templates/karpenter.sh_nodepools.yaml
  hack/validation/labels.sh
  hack/validation/requirements.sh
  pkg/apis/crds/karpenter.sh_nodeclaims.yaml
  pkg/apis/crds/karpenter.sh_nodepools.yaml
Labels: area/api-validation

#685 chore: Don't require access to Graph for role assignments
  Makefile-az.mk
Labels: area/security, area/devtools, area/ci

#690 chore: update devcontainer configuration
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  hack/toolchain.sh
Labels: area/devtools

#697 feat: setting network plugin to none in the agentbaker contract if using overlay
  pkg/providers/imagefamily/bootstrap/aksbootstrap.go
  pkg/providers/instancetype/suite_test.go
  pkg/providers/launchtemplate/launchtemplate.go
Labels: area/networking

#675 feat: validation enforcing vnet guid is set for overlay cni clusters
  go.mod
  pkg/operator/operator.go
  pkg/operator/options/options_validation.go
  pkg/operator/options/suite_test.go
  pkg/providers/instancetype/suite_test.go
  pkg/test/options.go
Labels: area/networking, area/api-validation
