Repository Azure/karpenter-provider-azure, pull requests merged in 2025-01, with the labels that each got.

#638 chore: regenerate CRDs with the latest controller-gen
  charts/karpenter-crd/templates/karpenter.azure.com_aksnodeclasses.yaml
  pkg/apis/crds/karpenter.azure.com_aksnodeclasses.yaml
Labels: area/devtools

#633 fix: Resolve errors for vm resource not found
  pkg/providers/instance/armutils.go
  pkg/providers/instance/instance.go
Labels: area/error-handling

#643 fix: disabling leader election
  karpenter-values-template.yaml
Labels: area/devtools

#637 fix: ZonalAllocationFailure handling (and general cleanup of zone name handling)
  pkg/cloudprovider/cloudprovider.go
  pkg/fake/types.go
  pkg/providers/instance/instance.go
  pkg/providers/instance/instance_test.go
  pkg/providers/instancetype/instancetypes.go
  pkg/providers/instancetype/suite_test.go
  pkg/test/expectations/expectations.go
  pkg/utils/zone.go
  pkg/utils/zone_test.go
Labels: area/availability-zones, area/error-handling

#647 chore: regenerate CRDs with the latest controller-gen
  charts/karpenter-crd/templates/karpenter.azure.com_aksnodeclasses.yaml
  pkg/apis/crds/karpenter.azure.com_aksnodeclasses.yaml
Labels: area/devtools

#648 fix(e2e): remove drift feature gate override
  test/suites/drift/suite_test.go
Labels: area/e2e-testing, area/drift

#644 docs: updating limitations
  README.md
Labels: size/XS, area/documentation

#657 [release 0.6.x] fix: exclude SKUs without compatible VM image and fix GPU bootstrap
  .pre-commit-config.yaml
  go.mod
  hack/codegen.sh
  pkg/fake/zz_generated.sku.eastus.go
  pkg/fake/zz_generated.sku.westcentralus.go
  pkg/providers/imagefamily/azlinux.go
  pkg/providers/imagefamily/bootstrap/aksbootstrap.go
  pkg/providers/imagefamily/bootstrap/bootstrap.go
  pkg/providers/imagefamily/bootstrap/cse_cmd.sh.gtpl
  pkg/providers/imagefamily/ubuntu_2204.go
  pkg/providers/instancetype/instancetypes.go
  pkg/providers/instancetype/suite_test.go
  pkg/providers/launchtemplate/launchtemplate.go
  pkg/providers/launchtemplate/parameters/types.go
  pkg/utils/gpu.go
  pkg/utils/gpu_test.go
  pkg/utils/supported-gpus.yaml
  typos.toml
Labels: area/vm-images, area/provisioning

#658 [release-v0.6.x] fix: ZonalAllocationFailure handling (and general cleanup of zone name handling)
  .golangci.yaml
  .pre-commit-config.yaml
  hack/code/instancetype_testdata_gen/main.go
  hack/code/prices_gen/main.go
  hack/codegen.sh
  hack/toolchain.sh
  pkg/cloudprovider/cloudprovider.go
  pkg/fake/types.go
  pkg/providers/instance/instance.go
  pkg/providers/instance/instance_test.go
  pkg/providers/instancetype/instancetypes.go
  pkg/providers/instancetype/suite_test.go
  pkg/test/expectations/expectations.go
  pkg/utils/zone.go
  pkg/utils/zone_test.go
Labels: area/availability-zones, area/error-handling

#659 [release-v0.6.x] fix: Resolve errors for resource not found (#633)
  pkg/providers/instance/armutils.go
  pkg/providers/instance/instance.go
Labels: area/error-handling

#642 fix: properly garbage collecting orphaned network interfaces
  pkg/cloudprovider/cloudprovider.go
  pkg/cloudprovider/suite_test.go
  pkg/controllers/controllers.go
  pkg/controllers/nodeclaim/garbagecollection/instance_garbagecollection.go
  pkg/controllers/nodeclaim/garbagecollection/nic_garbagecollection.go
  pkg/controllers/nodeclaim/garbagecollection/suite_test.go
  pkg/fake/azureresourcegraphapi.go
  pkg/fake/azureresourcegraphapi_test.go
  pkg/fake/networkinterfaceapi.go
  pkg/providers/instance/azureresourcegraphlist.go
  pkg/providers/instance/azureresourcegraphutils.go
  pkg/providers/instance/azureresourcemanagerutils.go
  pkg/providers/instance/instance.go
  pkg/providers/instance/instance_test.go
  pkg/providers/instance/suite_test.go
  pkg/test/environment.go
  pkg/test/expectations/expectations.go
  pkg/test/networkinterfaces.go
  pkg/test/utils.go
  pkg/test/virtualmachines.go
Labels: area/networking, area/provisioning, area/error-handling

#670 refactor: network interface garbage collection followup
  pkg/controllers/nodeclaim/garbagecollection/suite_test.go
  pkg/providers/instance/instance.go
Labels: area/networking, kind/cleanup

#668 [release-v0.6.x] fix: properly garbage collecting orphaned network interfaces (#642)
  pkg/cloudprovider/cloudprovider.go
  pkg/cloudprovider/suite_test.go
  pkg/controllers/controllers.go
  pkg/controllers/nodeclaim/garbagecollection/instance_garbagecollection.go
  pkg/controllers/nodeclaim/garbagecollection/nic_garbagecollection.go
  pkg/controllers/nodeclaim/garbagecollection/suite_test.go
  pkg/fake/azureresourcegraphapi.go
  pkg/fake/azureresourcegraphapi_test.go
  pkg/fake/networkinterfaceapi.go
  pkg/providers/instance/azureresourcegraphlist.go
  pkg/providers/instance/azureresourcegraphutils.go
  pkg/providers/instance/azureresourcemanagerutils.go
  pkg/providers/instance/instance.go
  pkg/providers/instance/instance_test.go
  pkg/providers/instance/suite_test.go
  pkg/test/environment.go
  pkg/test/expectations/expectations.go
  pkg/test/networkinterfaces.go
  pkg/test/utils.go
  pkg/test/virtualmachines.go
Labels: area/networking, area/error-handling
