Repository Azure/karpenter-provider-azure, pull requests merged in 2025-07, with the labels that each got.

#1020 fix: NAP supports nsg provider now, so we can run the nsg provider check in NAP
  test/suites/integration/subnet_test.go
Labels: area/security, area/e2e-testing

#1028 chore: remove redundant logging in provider layer
  pkg/providers/instance/instance.go
  pkg/providers/instance/resperrorhandlers.go
Labels: area/logging

#1036 chore: bump `sig.k8s.io/karpenter` to v1.6.0
  go.mod
  go.sum
Labels: area/dependency

#1049 chore: update devcontainer features
  .devcontainer/claude-code-copilot-api/devcontainer.json
  .devcontainer/devcontainer.json
  .gitignore
Labels: area/devtools

#1060 chore: bump sig.k8s.io/karpenter to v1.6.1
  go.mod
  go.sum
Labels: area/dependency
