Repository Azure/karpenter-provider-azure, pull requests merged in 2025-06, with the labels that each got.

#953 chore: add release-assets.githubusercontent.com to allowed-endpoints
  .github/workflows/ci-test.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/deflake.yml
  .github/workflows/e2e.yaml
Labels: area/security, area/ci

#928 fix: Propagate missing kubelet flags to node bootstrap variables
  pkg/providers/imagefamily/bootstrap/aksbootstrap.go
  pkg/providers/imagefamily/bootstrap/aksbootstrap_test.go
  pkg/providers/instancetype/suite_test.go
Labels: area/bootstrap, area/aksnodeclass

#914 feat: support Azure Linux v3 (from AKS 1.32)
  pkg/fake/nodeimageversionsapi.go
  pkg/providers/imagefamily/azlinux3.go
  pkg/providers/imagefamily/image.go
  pkg/providers/imagefamily/nodeimage.go
  pkg/providers/imagefamily/nodeimage_test.go
  pkg/providers/imagefamily/resolver.go
  pkg/providers/imagefamily/utils.go
  pkg/providers/instancetype/suite_test.go
  test/suites/kubernetesupgrade/suite_test.go
Labels: area/vm-images, area/upgrade, area/provisioning

#952 chore: update nodeimageversions fake data
  Makefile-az.mk
  pkg/fake/nodeimageversionsapi.go
  pkg/fake/nodeimageversionsapi_test.go
  pkg/providers/imagefamily/nodeimage_test.go
Labels: area/vm-images, area/testing

#958 fix: update devcontainer features
  .devcontainer/devcontainer.json
Labels: area/devtools

#940 fix: supporting Ephemeral OS Disk placement
  hack/codegen.sh
  pkg/cloudprovider/cloudprovider.go
  pkg/controllers/nodeclaim/garbagecollection/suite_test.go
  pkg/controllers/nodeclaim/inplaceupdate/controller.go
  pkg/controllers/nodeclaim/inplaceupdate/suite_test.go
  pkg/controllers/nodeclaim/inplaceupdate/utils.go
  pkg/fake/azureresourcegraphapi.go
  pkg/fake/azureresourcegraphapi_test.go
  pkg/fake/pricingapi.go
  pkg/fake/skus_test.go
  pkg/fake/virtualmachineextensionsapi.go
  pkg/fake/virtualmachinesapi.go
  pkg/fake/virtualmachinesapi_test.go
  pkg/fake/zz_generated.sku.southcentralus.go
  pkg/operator/operator.go
  pkg/providers/imagefamily/resolver.go
  pkg/providers/instance/azure_client.go
  pkg/providers/instance/azureresourcegraphlist.go
  pkg/providers/instance/azureresourcemanagerutils.go
  pkg/providers/instance/instance.go
  pkg/providers/instance/instance_test.go
  pkg/providers/instancetype/instancetype.go
  pkg/providers/instancetype/instancetypes.go
  pkg/providers/instancetype/suite_test.go
  pkg/providers/launchtemplate/launchtemplate.go
  pkg/providers/launchtemplate/parameters/types.go
  pkg/providers/pricing/zz_generated.pricing.go
  pkg/test/environment.go
  pkg/test/expectations/expectations.go
  pkg/test/virtualmachines.go
  pkg/utils/utils.go
  pkg/utils/zone.go
  pkg/utils/zone_test.go
  test/pkg/environment/azure/environment.go
  test/pkg/environment/azure/utils.go
  test/suites/nodeclaim/eph_osdisk_test.go
  test/suites/scheduling/suite_test.go
Labels: area/storage, area/provisioning

#1011 fix: don't use ephemeral disk if not supported
  pkg/providers/instancetype/instancetype.go
  pkg/providers/instancetype/instancetypes.go
  pkg/providers/instancetype/suite_test.go
  test/suites/nodeclaim/eph_osdisk_test.go
Labels: area/storage, area/provisioning

#1013 chore: set user agent on release
  Makefile
  hack/release/common.sh
  pkg/auth/util.go
Labels: area/release
