Repository Azure/karpenter-provider-azure, pull requests merged in 2025-05, with the labels that each got.

#855 fix: testing duration in e2e
  test/suites/integration/repair_policy_test.go
Labels: area/e2e-testing

#821 test(e2e): add scheduling suite
  .github/workflows/e2e-matrix.yaml
  test/pkg/environment/azure/environment.go
  test/pkg/environment/azure/expectations.go
  test/suites/scheduling/suite_test.go
Labels: area/e2e-testing, area/scheduling

#860 test(e2e): fix drift suite
  test/suites/drift/suite_test.go
Labels: area/e2e-testing, area/drift

#857 test: node auto repair doesn't remove our gpus
  test/suites/gpu/suite_test.go
Labels: area/gpu

#844 test(e2e): add consolidation suite
  .github/workflows/e2e-matrix.yaml
  test/suites/consolidation/suite_test.go
Labels: area/e2e-testing, area/consolidation

#861 test: fix logging after cancel
  pkg/providers/pricing/pricing.go
Labels: area/testing, area/pricing, area/ci

#805 feat: support zone constraint in NodePool requirements
  Makefile
  charts/karpenter-crd/templates/karpenter.azure.com_aksnodeclasses.yaml
  charts/karpenter-crd/templates/karpenter.sh_nodeclaims.yaml
  charts/karpenter-crd/templates/karpenter.sh_nodepools.yaml
  hack/validation/common.sh
  pkg/apis/crds/karpenter.azure.com_aksnodeclasses.yaml
  pkg/apis/crds/karpenter.sh_nodeclaims.yaml
  pkg/apis/crds/karpenter.sh_nodepools.yaml
  pkg/apis/v1alpha2/labels.go
  pkg/cloudprovider/cloudprovider.go
  pkg/providers/instancetype/suite_test.go
  test/pkg/environment/common/expectations.go
  test/suites/integration/zone_constraints_test.go
  test/suites/scheduling/suite_test.go
Labels: kind/api-change, area/api-validation, area/availability-zones, area/api

#872 BREAKING CHANGE: remove support for `sku-encryptionathost-capable` label/selector
  charts/karpenter-crd/templates/karpenter.sh_nodeclaims.yaml
  charts/karpenter-crd/templates/karpenter.sh_nodepools.yaml
  hack/validation/labels.sh
  hack/validation/requirements.sh
  pkg/apis/crds/karpenter.sh_nodeclaims.yaml
  pkg/apis/crds/karpenter.sh_nodepools.yaml
  pkg/apis/v1alpha2/labels.go
  pkg/providers/instancetype/instancetype.go
  pkg/providers/instancetype/suite_test.go
  test/suites/scheduling/suite_test.go
Labels: kind/api-change, area/api

#868 fix: use defaults for SDK retry options
  pkg/utils/opts/armopts.go
Labels: area/deprovisioning, area/provisioning, area/performance

#882 feat: switch artifact streaming on
  pkg/providers/imagefamily/customscriptsbootstrap/provisionclientbootstrap.go
Labels: area/provisioning, area/performance

#881 chore: bump GPU driver versions
  pkg/utils/gpu.go
Labels: area/gpu, area/dependency

#884 fix: make artifact streaming conditional on architecture and distribution
  pkg/providers/imagefamily/customscriptsbootstrap/provisionclientbootstrap.go
Labels: area/provisioning, area/performance

#892 feat: handle OverconstrainedZonalAllocation, OverconstrainedAllocation and AllocationFailure errors when creating new instances
  go.mod
  go.sum
  pkg/providers/instance/instance.go
  pkg/providers/instancetype/suite_test.go
Labels: area/provisioning, area/availability-zones, area/error-handling

#891 fix(drift): improve NotFound and Deleting Nodes case in Drift
  pkg/cloudprovider/drift.go
  pkg/cloudprovider/suite_test.go
  pkg/test/utils.go
Labels: area/provisioning, area/drift

#893 chore: refresh (and backfill missing) pricing
  hack/code/prices_gen/main.go
  pkg/providers/instancetype/instancetypes.go
  pkg/providers/instancetype/skus.go
  pkg/providers/instancetype/skus_test.go
  pkg/providers/pricing/client/pricingapi.go
  pkg/providers/pricing/pricing.go
  pkg/providers/pricing/skus_missing_price.go
  pkg/providers/pricing/suite_test.go
  pkg/providers/pricing/zz_generated.pricing.go
Labels: area/pricing

#885 feat: default ENABLE_KUBELET_SERVING_CERTIFICATE_ROTATION for self-hosted
  pkg/providers/imagefamily/bootstrap/aksbootstrap.go
  pkg/providers/imagefamily/bootstrap/cse_cmd.sh.gtpl
  pkg/providers/imagefamily/bootstrap/staticvalues.go
Labels: area/provisioning

#903 feat: on publishing images, check if tag already exists
  hack/release/common.sh
Labels: area/security, area/release

#912 fix: capture both values for boolean requirements
  pkg/providers/instancetype/instancetype.go
  pkg/providers/instancetype/suite_test.go
Labels: area/api

#908 fix: adjust TTL for unavailable offerings when allocation error happens
  pkg/providers/instance/instance.go
  pkg/providers/instance/instance_test.go
Labels: area/error-handling

#907 feat: support `--linux-admin-username` option
  pkg/operator/options/options.go
  pkg/operator/options/options_validation.go
  pkg/operator/options/suite_test.go
  pkg/providers/instance/instance.go
  pkg/providers/instance/suite_test.go
  pkg/test/options.go
Labels: area/security, area/provisioning, area/global-config

#909 feat: add trivy scans
  .github/actions/install-deps/action.yaml
  .github/workflows/ci-test.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/deflake.yml
  .github/workflows/e2e.yaml
  Makefile
  hack/release/common.sh
  hack/toolchain.sh
Labels: area/security

#921 chore: change base image to Azure Linux 3
  .ko.yaml
Labels: area/artifacts, area/dependency

#911 chore: add 1.33 to test matrix
  .github/workflows/ci-test.yml
  pkg/providers/imagefamily/bootstrap/aksbootstrap.go
  pkg/providers/imagefamily/bootstrap/aksbootstrap_test.go
Labels: area/testing, area/ci
